Repository c4urself/bump2version, pull requests merged in 2020-01, with the labels that each got.

#92 Fix bug in README example
  README.md
Labels: bug, documentation

#115 Add go.mod example to README.md
  README.md
Labels: documentation, requires-decision

#47 Allow arbitrary arguments to commit command
  README.md
  bumpversion/cli.py
  bumpversion/vcs.py
Labels: feature, feature-approved

#108 Drop support for EOL Python 2.7
  .travis.yml
  Dockerfile
  Makefile
  README.md
  appveyor.yml
  bumpversion/cli.py
  bumpversion/compat.py
  bumpversion/functions.py
  bumpversion/utils.py
  bumpversion/vcs.py
  bumpversion/version_part.py
  setup.py
  tests/test_cli.py
  tox.ini
Labels: feature-approved

#98 Fix newlines in config files
  bumpversion/cli.py
  tests/test_cli.py
Labels: feature, requires-review

#129 Mention similar / related tools in a separate Markdown document
  README.md
  RELATED.md
Labels: ready-for-merge, requires-decision
