Repository c4urself/bump2version, pull requests merged in 2021-01, with the labels that each got.

#187 Handle ENOTDIR error when checking for VCS
  bumpversion/vcs.py
Labels: bug

#177 adding semantic version example
  docs/examples/semantic-versioning/1.0.0/.bumpversion.cfg
  docs/examples/semantic-versioning/1.0.0/VERSION.txt
  docs/examples/semantic-versioning/1.0.0/bump-patch/ARGUMENTS.txt
  docs/examples/semantic-versioning/1.0.0/bump-patch/VERSION.txt
  docs/examples/semantic-versioning/1.0.1-dev1/.bumpversion.cfg
  docs/examples/semantic-versioning/1.0.1-dev1/VERSION.txt
  docs/examples/semantic-versioning/1.0.1-dev1/bump-build/ARGUMENTS.txt
  docs/examples/semantic-versioning/1.0.1-dev1/bump-build/VERSION.txt
  docs/examples/semantic-versioning/1.0.1-dev1/bump-release/ARGUMENTS.txt
  docs/examples/semantic-versioning/1.0.1-dev1/bump-release/VERSION.txt
  docs/examples/semantic-versioning/1.0.1-rc1/.bumpversion.cfg
  docs/examples/semantic-versioning/1.0.1-rc1/VERSION.txt
  docs/examples/semantic-versioning/1.0.1-rc1/bump-build/ARGUMENTS.txt
  docs/examples/semantic-versioning/1.0.1-rc1/bump-build/VERSION.txt
  docs/examples/semantic-versioning/1.0.1-rc1/bump-release/ARGUMENTS.txt
  docs/examples/semantic-versioning/1.0.1-rc1/bump-release/VERSION.txt
  docs/examples/semantic-versioning/README.md
Labels: documentation, feature-approved, ready-for-merge

#172 Add an example to the docs around custom search patterns that need to match literal quotes
  README.md
Labels: documentation, ready-for-merge

#167 Prefer the shortest required pattern for version
  bumpversion/version_part.py
  tests/test-cases/use-shortest-pattern/arguments.txt
  tests/test-cases/use-shortest-pattern/input/.bumpversion.cfg
  tests/test-cases/use-shortest-pattern/input/package.json
  tests/test-cases/use-shortest-pattern/output/.bumpversion.cfg
  tests/test-cases/use-shortest-pattern/output/package.json
  tests/test-cases/use-shortest-pattern/run/.bumpversion.cfg
  tests/test-cases/use-shortest-pattern/run/package.json
  tests/test_cli.py
Labels: bug, ready-for-merge

#191 Added example for first_value, and elaborated on optional_value
  README.md
Labels: documentation, ready-for-merge

#143 Add test requirements including minimal versions
  setup.py
  tox.ini
Labels: feature-approved, packaging, ready-for-merge
